use std::str::FromStr;

use anyhow::Result;
use gettextrs::gettext;
use serde::Deserialize;

use super::Restorable;
use crate::models::{Method, OTPUri};

pub struct Yandex;

impl Restorable for Yandex {
    const ENCRYPTABLE: bool = false;
    const SCANNABLE: bool = false;
    const IDENTIFIER: &'static str = "yandex-txt";
    type Item = OTPUri;

    fn title() -> String {
        gettext("Yandex Key")
    }

    fn subtitle() -> String {
        gettext("From a plain-text file generated by Yandex Key")
    }

    fn restore_from_data(from: &[u8], _key: Option<&str>) -> Result<Vec<Self::Item>> {
        #[derive(Deserialize)]
        struct Entry {
            #[serde(rename = "techInfo")]
            tech_info: String,
            #[serde(rename = "warning")]
            _warning: Option<String>,
        }

        let raw: Vec<Entry> = serde_json::from_slice(from)?;
        let mut items = Vec::with_capacity(raw.len());

        for entry in raw {
            let Ok(mut normalized) = OTPUri::from_str(&entry.tech_info) else {
                continue;
            };

            // Working with yaotp is not currently supported
            if !matches!(normalized.method, Method::TOTP | Method::HOTP) {
                continue;
            }

            match normalized.method {
                Method::TOTP => {
                    normalized.digits = None;
                    normalized.counter = None;
                }
                Method::HOTP => {
                    normalized.counter.get_or_insert(0);
                }
                Method::Steam => {
                    continue;
                }
            }

            items.push(normalized);
        }

        Ok(items)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        backup::RestorableItem,
        models::{Algorithm, Method},
    };

    #[test]
    fn parse_yandex_json_anonymous() {
        let data = r#"[
            {
                "techInfo": "otpauth://yaotp/user?chars=alpha&secret=REDACTEDSECRET&creation_type=unknown"
            },
            {
                "name": "user1@example.com",
                "secret": "ABCDEFGHIJKLMNOP",
                "techInfo": "otpauth://totp/Issuer1:user1@example.com?algorithm=SHA256&digits=8&secret=ABCDEFGHIJKLMNOP&issuer=Issuer1&period=45"
            },
            {
                "name": "user2@example.com",
                "secret": "QRSTUVWXYZ123456",
                "techInfo": "otpauth://hotp/Issuer2:user2@example.com?algorithm=SHA512&digits=7&secret=QRSTUVWXYZ123456&issuer=Issuer2&counter=5"
            }
        ]"#;

        // Working with yaotp is not currently supported
        let items = Yandex::restore_from_data(data.as_bytes(), None).unwrap();
        assert_eq!(items.len(), 2);

        let totp = items.iter().find(|i| i.method() == Method::TOTP).unwrap();
        assert_eq!(totp.issuer(), "Issuer1");
        assert_eq!(totp.account(), "user1@example.com");
        assert_eq!(totp.secret(), "ABCDEFGHIJKLMNOP");
        assert_eq!(totp.method(), Method::TOTP);
        assert_eq!(totp.algorithm(), Algorithm::SHA256);
        assert_eq!(totp.digits(), None);
        assert_eq!(totp.period(), Some(45));

        let hotp = items.iter().find(|i| i.method() == Method::HOTP).unwrap();
        assert_eq!(hotp.issuer(), "Issuer2");
        assert_eq!(hotp.account(), "user2@example.com");
        assert_eq!(hotp.secret(), "QRSTUVWXYZ123456");
        assert_eq!(hotp.method(), Method::HOTP);
        assert_eq!(hotp.algorithm(), Algorithm::SHA512);
        assert_eq!(hotp.digits(), Some(7));
        assert_eq!(hotp.counter(), Some(5));
    }
}
